---
- name: Install Apache and Ping Windows PC  # Training modules when, block, copy, apt, yum, service, handlers
  hosts: all

  vars:
    source_file: ../site/index.html
    destin_file: /var/www/html
  
  tasks:

  - block:  # ==== block for Debian ====
     - name: 1. Install Apache Web Server for Debian
       apt:
         name: apache2
         state: latest

     - name: 2. Start and enable boot Apache
       service:
         name: apache2
         state: started
         enabled: yes

     - name: 3. Copy Index.html to server
       copy:
         src:   "{{ source_file }}"
         dest:  "{{ destin_file }}"
         mode: 0555
       notify: Restart Apache Debian
      
    become: yes
    when: ansible_os_family == "Debian"

  - block: # ==== block for Redhat ====
     - name: 1. Install Apache Web Server for Redhat
       yum:
         name: httpd
         state: latest

     - name: 2. Start and enable boot Apache
       service:
         name: httpd
         state: started
         enabled: yes

     - name: 3. Copy Index.html to server
       copy:
         src:   "{{ source_file }}"
         dest:  "{{ destin_file }}"
         mode: 0555
       notify: Restart Apache Redhat
       
    become: yes
    when: ansible_os_family == "RedHat"

  - block: # ===== block forWindows =====
    - name: 4. Ping windows PC all commands WORK
      win_ping:
    when: ansible_os_family == "Windows"

  handlers:
  - name: Restart Apache Debian
    service:
      name: apache2
      state: restarted

  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted
