---
# Training modules: vars, when, block, copy, apt, yum, service,
# handlers, notify, template (jinja .j2)
- name: Install Apache to all linux servers
  hosts: all_linux
  become: yes

  vars:
    source_folder: ../site/
    destin_folder: /var/www/html
    resourse_folder: ../site/Resourse
    
  
  tasks:
###################################################
  - block: #Deb block
    - name: 1. Install Apache Web Server fot Debian
      apt:
         name: apache2
         state: latest

    - name: 2. Start and enable boot Apache
      service:
         name: apache2
         state: started
         enabled: yes
    when: ansible_os_family == "Debian"

####################################################

  - block: #Red block
    - name: 1. Install Apache Web Server for Redhat
      yum:
         name: httpd
         state: latest

    - name: 2. Start and enable boot Apache
      service:
         name: httpd
         state: started
         enabled: yes

    when: ansible_os_family == "RedHat"

#####################################################
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /var/www/html/
      state: directory
      mode: '0755'

  - name: del for testing
    shell:   rm -rf /var/www/html/*
    
  - name: Generate Index.html
    template: 
      src: "{{ source_folder }}/index.j2"
      dest: "{{ destin_folder }}/index.html"
      owner: andrew
      mode: 0644


  - name: 3. Copy Index.html to server
    copy:
      src:   "{{ resourse_folder }}"
      dest:  "{{ destin_folder }}"
      owner: andrew      
      mode: 0644
      

#       src:  "{{ source_folder }}/{{ item }}" # ITEM - >> loop env
#       dest:  "{{ destin_folder }}"
#       mode: 0644
#    loop:   # Передает значения в item
#        - "index.html"
#        - "Resourse/"
#        - "./Resourse/2.png"
#        - "./Resourse/3.png"
    notify:    #Notify + Handler
         - Restart Apache Debian
         - Restart Apache RedHat


#####################################################      
  
  handlers:
  - name: Restart Apache Debian
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"

  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"

